using System.IO;
using MergulhoVirtual.DesignSystem.Gallery;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.TextCore.LowLevel;
using UnityEngine.TextCore.Text;
using UnityEngine.UIElements;

namespace MergulhoVirtual.DesignSystem.Editor
{
    /// <summary>
    /// One-shot setup for everything in the design system that needs editor-side
    /// asset creation: TextCore font assets, the dp-calibrated PanelSettings, and
    /// the GalleryScene. Idempotent — safe to re-run after regenerating fonts or
    /// tokens.
    ///
    /// Run from the menu (Tools > Mergulho Virtual > Design System > Setup All)
    /// or headlessly, with the editor CLOSED:
    ///   make ds-setup
    ///   (= Unity -batchmode -quit -projectPath src/app/MergulhoVirtual
    ///      -executeMethod MergulhoVirtual.DesignSystem.Editor.DesignSystemSetup.SetupAll)
    /// </summary>
    public static class DesignSystemSetup
    {
        const string Root = "Assets/DesignSystem";
        const string PanelSettingsPath = Root + "/PanelSettings.asset";
        const string GalleryScenePath = Root + "/Gallery/GalleryScene.unity";
        const string LightThemePath = Root + "/Theme-Light.tss";
        const string DarkThemePath = Root + "/Theme-Dark.tss";
        const string GalleryStylesPath = Root + "/Gallery/Gallery.uss";

        /// <summary>
        /// Every TTF under Fonts/ that needs a TextCore SDF asset. UI Toolkit resolves
        /// font weight through a *separate asset per weight*, which is why Inter appears
        /// four times (400/500/600/700) — see DESIGN_IMPLEMENTATION.md §3.4.
        ///
        /// Inter is the brand face (referenced by Tokens/_typography.uss). Roboto is kept
        /// as the stock-M3 reference face: nothing in the shipped type scale points at it
        /// any more, so it can be dropped once no gallery/test fixture references it.
        /// </summary>
        static readonly string[] FontNames =
        {
            "Inter-Regular",
            "Inter-Medium",
            "Inter-SemiBold",
            "Inter-Bold",
            "Roboto-Regular",
            "Roboto-Medium",
            "Roboto-Bold",
            "MaterialSymbols",
        };

        [MenuItem("Tools/Mergulho Virtual/Design System/Setup All (fonts + panel + gallery)", priority = 200)]
        public static void SetupAll()
        {
            GenerateFontAssets();
            CreatePanelSettings();
            CreateGalleryScene();
            AssetDatabase.SaveAssets();
            Debug.Log("[DesignSystemSetup] Setup complete — open " + GalleryScenePath + " and press Play.");
        }

        // ====================================================================
        // Font assets: TTF → TextCore FontAsset (dynamic SDF), saved next to
        // the source. USS references them by path (url()), so the GUID churn
        // from delete+recreate is harmless; referencing USS/TSS files are
        // reimported afterwards so their url() resolutions refresh.
        // ====================================================================
        [MenuItem("Tools/Mergulho Virtual/Design System/Generate Font Assets", priority = 201)]
        public static void GenerateFontAssets()
        {
            foreach (var name in FontNames)
            {
                string ttfPath = $"{Root}/Fonts/{name}.ttf";
                string assetPath = $"{Root}/Fonts/{name}.asset";

                var font = AssetDatabase.LoadAssetAtPath<Font>(ttfPath);
                if (font == null)
                    throw new FileNotFoundException(
                        $"[DesignSystemSetup] {ttfPath} missing. Inter + Roboto TTFs are committed " +
                        "(re-download per tools/design_system/README.md); MaterialSymbols.ttf is " +
                        "generated by tools/design_system/subset_material_symbols.py.");

                if (AssetDatabase.LoadAssetAtPath<FontAsset>(assetPath) != null)
                    AssetDatabase.DeleteAsset(assetPath);

                var fontAsset = FontAsset.CreateFontAsset(
                    font, 90, 9, GlyphRenderMode.SDFAA, 1024, 1024,
                    AtlasPopulationMode.Dynamic, enableMultiAtlasSupport: true);
                fontAsset.name = name;
                AssetDatabase.CreateAsset(fontAsset, assetPath);

                if (fontAsset.material != null)
                {
                    fontAsset.material.name = name + " Material";
                    AssetDatabase.AddObjectToAsset(fontAsset.material, fontAsset);
                }
                if (fontAsset.atlasTextures != null)
                {
                    for (int i = 0; i < fontAsset.atlasTextures.Length; i++)
                    {
                        if (fontAsset.atlasTextures[i] == null) continue;
                        fontAsset.atlasTextures[i].name = $"{name} Atlas {i}";
                        AssetDatabase.AddObjectToAsset(fontAsset.atlasTextures[i], fontAsset);
                    }
                }
                Debug.Log($"[DesignSystemSetup] Font asset: {assetPath}");
            }

            AssetDatabase.SaveAssets();

            // Refresh every stylesheet that references the fonts via url().
            foreach (var guid in AssetDatabase.FindAssets("t:StyleSheet", new[] { Root }))
                AssetDatabase.ImportAsset(AssetDatabase.GUIDToAssetPath(guid));
        }

        // ====================================================================
        // PanelSettings calibrated so 1 USS px = 1 dp (Constant Physical Size
        // at 160 dpi — Android's dp definition). Updated in place if it exists
        // so scene references by GUID stay valid.
        // ====================================================================
        [MenuItem("Tools/Mergulho Virtual/Design System/Create Panel Settings", priority = 202)]
        public static void CreatePanelSettings()
        {
            var settings = AssetDatabase.LoadAssetAtPath<PanelSettings>(PanelSettingsPath);
            bool isNew = settings == null;
            if (isNew)
                settings = ScriptableObject.CreateInstance<PanelSettings>();

            settings.scaleMode = PanelScaleMode.ConstantPhysicalSize;
            settings.referenceDpi = 160f;
            settings.fallbackDpi = 160f;
            settings.themeStyleSheet = LoadRequired<ThemeStyleSheet>(LightThemePath);

            if (isNew)
                AssetDatabase.CreateAsset(settings, PanelSettingsPath);
            else
                EditorUtility.SetDirty(settings);
            Debug.Log($"[DesignSystemSetup] PanelSettings: {PanelSettingsPath} (1 USS px = 1 dp)");
        }

        // ====================================================================
        // GalleryScene: camera + UIDocument + GalleryController, fully wired.
        // ====================================================================
        [MenuItem("Tools/Mergulho Virtual/Design System/Create Gallery Scene", priority = 203)]
        public static void CreateGalleryScene()
        {
            if (!Application.isBatchMode)
            {
                if (File.Exists(GalleryScenePath) && !EditorUtility.DisplayDialog(
                        "Gallery Scene", "GalleryScene.unity already exists. Replace it?", "Replace", "Cancel"))
                    return;
                if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                    return;
            }

            var scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);

            var cameraGo = GameObject.Find("Main Camera");
            if (cameraGo != null && cameraGo.TryGetComponent<Camera>(out var camera))
            {
                camera.clearFlags = CameraClearFlags.SolidColor;
                camera.backgroundColor = new Color(0.06f, 0.09f, 0.10f, 1f);
            }

            var galleryGo = new GameObject("Gallery");
            var document = galleryGo.AddComponent<UIDocument>();
            document.panelSettings = LoadRequired<PanelSettings>(PanelSettingsPath);
            var controller = galleryGo.AddComponent<GalleryController>();

            var so = new SerializedObject(controller);
            so.FindProperty("document").objectReferenceValue = document;
            so.FindProperty("lightTheme").objectReferenceValue = LoadRequired<ThemeStyleSheet>(LightThemePath);
            so.FindProperty("darkTheme").objectReferenceValue = LoadRequired<ThemeStyleSheet>(DarkThemePath);
            so.FindProperty("galleryStyles").objectReferenceValue = LoadRequired<StyleSheet>(GalleryStylesPath);
            so.ApplyModifiedPropertiesWithoutUndo();

            EditorSceneManager.SaveScene(scene, GalleryScenePath);
            Debug.Log($"[DesignSystemSetup] Gallery scene: {GalleryScenePath}");
        }

        static T LoadRequired<T>(string path) where T : Object
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null)
                throw new FileNotFoundException($"[DesignSystemSetup] Required asset missing: {path}");
            return asset;
        }
    }
}
