using System;
using System.Collections.Generic;

namespace MergulhoVirtual.UI
{
    /// <summary>
    /// What one block of an article's body <i>is</i> — the in-memory form of the
    /// string discriminator on the wire (<c>"type": "paragraph"</c>).
    ///
    /// <para><b><see cref="Unknown"/> is the default and it is a
    /// forward-compatibility case, not a data error.</b> It means "this build does
    /// not understand this block type" — an <c>articles.json</c> generated by a
    /// newer <c>tools/build_articles.py</c>, running inside an older APK. Such a
    /// block must render as <b>nothing at all</b>: no placeholder, no "conteúdo
    /// indisponível" line, no empty card with padding. The whole reason the
    /// discriminator is a <i>string</i> on the wire and an <i>enum</i> in memory is
    /// that an unrecognised token can then degrade to silence instead of failing the
    /// parse, so a newer content file drops its unknown blocks and still shows every
    /// block the build does know.</para>
    ///
    /// <para>The loader keeps unknown blocks in <see cref="Article.Blocks"/> rather
    /// than dropping them, so diagnostics and a future build can still see them;
    /// <see cref="ArticleBlock.IsRenderable"/> is the flag that filters them out, and
    /// <c>ArticleViewModel.Blocks</c> is where that filter is actually applied so a
    /// screen cannot forget to.</para>
    ///
    /// <para>Distinguish this from <see cref="BeachRiskLevel.Unknown"/>, which means
    /// "a human has not filled this in yet". Nothing here is unfilled — a block that
    /// exists was authored; this build just cannot read it.</para>
    /// </summary>
    public enum ArticleBlockKind
    {
        Unknown = 0,

        /// <summary><c>## Texto</c> / <c>### Texto</c> — <see cref="ArticleBlock.Level"/> is 2 or 3.</summary>
        Heading,

        /// <summary>Blank-line-separated prose. May carry <c>&lt;b&gt; &lt;i&gt; &lt;u&gt; &lt;a href&gt;</c>.</summary>
        Paragraph,

        /// <summary><c>- item</c> run — <see cref="ArticleBlock.Items"/>.</summary>
        BulletList,

        /// <summary><c>1. item</c> run — <see cref="ArticleBlock.Items"/>, numbered by the screen.</summary>
        NumberedList,

        /// <summary><c>&gt; [!info] Texto</c> — tinted inline notice, see <see cref="ArticleBlock.Tone"/>.</summary>
        Callout,

        /// <summary><c>&gt; Texto</c> with an optional <see cref="ArticleBlock.Attribution"/>.</summary>
        Quote,

        /// <summary>A Resources sprite with an optional caption and credit.</summary>
        Image,

        /// <summary>A public HTTPS MP4 with an optional title.</summary>
        Video,

        /// <summary>A link to the Espécie screen, by <see cref="ArticleBlock.SpeciesKey"/>.</summary>
        SpeciesRef,

        /// <summary>A link to Praia detalhe, by <see cref="ArticleBlock.BeachName"/>.</summary>
        BeachRef,
    }

    /// <summary>
    /// A callout's severity. <b>There is deliberately no <c>Unknown</c> member.</b>
    /// A callout whose <c>tone</c> token this build cannot read still has text worth
    /// showing, so the loader warns once and falls back to <see cref="Info"/> — the
    /// neutral tone, which cannot over- or under-state a warning the author wrote.
    /// Losing the tint is a cosmetic degradation; dropping the sentence would not be.
    ///
    /// <para>Contrast the block <i>kind</i>, where <c>Unknown</c> does exist: there,
    /// this build does not know what the payload means at all, so it cannot render
    /// anything honest.</para>
    /// </summary>
    public enum ArticleCalloutTone
    {
        Info = 0,
        Warning,
        Success,
        Error,
    }

    /// <summary>
    /// One block of an article body — the engine-free mirror of a <c>blocks[]</c>
    /// entry in <c>Assets/Resources/articles.json</c>.
    ///
    /// <para><b>Flat, with every field of the union on every instance</b>, because
    /// <c>JsonUtility</c> cannot deserialise polymorphically (the same reason
    /// <c>JobEnvelope</c> exists for <c>Job</c> subclasses). Which fields carry
    /// meaning is decided by <see cref="Kind"/> and nothing else: <see cref="Level"/>
    /// is meaningless on a paragraph, <see cref="Tone"/> is meaningless on anything
    /// but a callout, and reading one anyway gets you a C# default rather than an
    /// error. Ask <see cref="Kind"/> first.</para>
    ///
    /// <para>Every optional string has a <c>Has*</c> companion and every list
    /// defaults to empty rather than null, so a screen binds without null-checking —
    /// the same contract <see cref="BeachContent"/> sets.</para>
    /// </summary>
    public sealed class ArticleBlock
    {
        /// <summary>What this block is. See <see cref="ArticleBlockKind.Unknown"/>
        /// before assuming a block is always one of the known kinds.</summary>
        public ArticleBlockKind Kind;

        /// <summary>
        /// Heading level, 2 or 3 — only meaningful when <see cref="Kind"/> is
        /// <see cref="ArticleBlockKind.Heading"/>. Level 1 does not exist: the
        /// article's own title comes from front matter, and a body <c>#</c> is an
        /// error the build script refuses. The loader clamps anything out of range
        /// into 2–3 rather than emitting a level no stylesheet has a rule for.
        /// </summary>
        public int Level;

        /// <summary>
        /// The block's prose — paragraph, heading, callout or quote text.
        ///
        /// <para><b>It may contain rich text, and only four tags.</b> The build
        /// script neutralises every author <c>&lt;</c> <i>before</i> inserting its
        /// own markup — each one is wrapped in <c>&lt;noparse&gt;</c>, which renders
        /// a visible <c>&lt;</c> that cannot open a tag — so the only tags that can
        /// reach the UI Toolkit text generator are <c>&lt;b&gt;</c>,
        /// <c>&lt;i&gt;</c>, <c>&lt;u&gt;</c> (the whole of a link's visual
        /// treatment) and <c>&lt;a href&gt;</c>. <c>&amp;</c> and <c>&gt;</c> are
        /// left alone: neither can open a tag, and UI Toolkit decodes no HTML
        /// entities, so an escaped one would print as its literal characters. A
        /// screen must render this <b>as-is</b> — never re-escape it (which would
        /// print the tags) and never concatenate unescaped text into it.</para>
        /// </summary>
        public string Text;

        /// <summary>List rows, for <see cref="ArticleBlockKind.BulletList"/> and
        /// <see cref="ArticleBlockKind.NumberedList"/> only. Never null; empty on
        /// every other kind. Rows may carry the same inline tags as
        /// <see cref="Text"/>.</summary>
        public IReadOnlyList<string> Items = Array.Empty<string>();

        /// <summary>Callout severity; meaningless unless <see cref="Kind"/> is
        /// <see cref="ArticleBlockKind.Callout"/>, where it defaults to
        /// <see cref="ArticleCalloutTone.Info"/>.</summary>
        public ArticleCalloutTone Tone;

        /// <summary>Who said it, for a <see cref="ArticleBlockKind.Quote"/> — the
        /// author text with the leading dash stripped by the build script. Optional:
        /// an unattributed pull quote is legitimate.</summary>
        public string Attribution;

        /// <summary>
        /// Sprite path for an <see cref="ArticleBlockKind.Image"/>, as
        /// <c>Resources.Load&lt;Sprite&gt;</c> wants it: relative to
        /// <c>Assets/Resources/</c> and <b>without the extension</b>
        /// ("Beaches/praia_do_sancho"). A lookup key, never rendered.
        /// </summary>
        public string Src;

        /// <summary>Visible caption under an image. Optional — a decorative image
        /// carries none, and the screen then draws no caption line.</summary>
        public string Caption;

        /// <summary>
        /// Attribution for an image ("Foto: Autor / CC BY-SA 4.0 (Wikimedia
        /// Commons)"). Optional only because a project-owned photo needs none — when
        /// present it is a <b>licence condition</b>, so it is never dimmed with
        /// <c>opacity</c> and never truncated.
        /// </summary>
        public string Credit;

        /// <summary>Stream URL for a <see cref="ArticleBlockKind.Video"/> — a public
        /// HTTPS object in the <c>conteudos-educacionais</c> bucket. Handed to the
        /// player, never rendered.</summary>
        public string Url;

        /// <summary>Caption of a video card. Optional.</summary>
        public string Title;

        /// <summary>Catalog key for a <see cref="ArticleBlockKind.SpeciesRef"/> — an
        /// <c>AnimalDef</c> asset file name ("tiger_shark"). ASCII, English, a lookup
        /// key: it must never reach the screen's text, which uses the catalog's own
        /// pt-BR <c>DisplayName</c>.</summary>
        public string SpeciesKey;

        /// <summary>places.json <c>name</c> for a <see cref="ArticleBlockKind.BeachRef"/>
        /// ("Sueste Beach"). Also a machine key — several are English or awkward,
        /// which is exactly why <c>BeachInfo.DisplayName</c> exists. Never
        /// rendered.</summary>
        public string BeachName;

        public bool HasText => !string.IsNullOrWhiteSpace(Text);
        public bool HasItems => Items != null && Items.Count > 0;
        public bool HasAttribution => !string.IsNullOrWhiteSpace(Attribution);
        public bool HasSrc => !string.IsNullOrWhiteSpace(Src);
        public bool HasCaption => !string.IsNullOrWhiteSpace(Caption);
        public bool HasCredit => !string.IsNullOrWhiteSpace(Credit);
        public bool HasUrl => !string.IsNullOrWhiteSpace(Url);
        public bool HasTitle => !string.IsNullOrWhiteSpace(Title);
        public bool HasSpeciesKey => !string.IsNullOrWhiteSpace(SpeciesKey);
        public bool HasBeachName => !string.IsNullOrWhiteSpace(BeachName);

        /// <summary>
        /// This build knows what the block is <b>and</b> it carries the payload that
        /// kind needs. Everything else is dropped rather than drawn: an unknown kind
        /// (a newer content file — see <see cref="ArticleBlockKind.Unknown"/>), a
        /// paragraph whose text is blank, a bullet list with no rows, an image with
        /// no <see cref="Src"/>, a species reference with no key.
        ///
        /// <para>Keeping the test here rather than in a screen is deliberate: it is
        /// data-shaped, it is unit-testable with no panel, and there is exactly one
        /// of it — so a second screen rendering articles cannot arrive at a different
        /// answer. <c>ArticleViewModel.Blocks</c> applies it.</para>
        /// </summary>
        public bool IsRenderable
        {
            get
            {
                switch (Kind)
                {
                    case ArticleBlockKind.Heading:
                    case ArticleBlockKind.Paragraph:
                    case ArticleBlockKind.Callout:
                    case ArticleBlockKind.Quote:
                        return HasText;
                    case ArticleBlockKind.BulletList:
                    case ArticleBlockKind.NumberedList:
                        return HasItems;
                    case ArticleBlockKind.Image:
                        return HasSrc;
                    case ArticleBlockKind.Video:
                        return HasUrl;
                    case ArticleBlockKind.SpeciesRef:
                        return HasSpeciesKey;
                    case ArticleBlockKind.BeachRef:
                        return HasBeachName;
                    default:
                        return false;
                }
            }
        }
    }

    /// <summary>
    /// One article as the <b>index</b> sees it — everything the card on the
    /// "Conteúdo educativo" list shows, and none of the body. Mirror of an
    /// <c>articles[]</c> entry in <c>Assets/Resources/articles.json</c> minus
    /// <c>blocks</c>.
    ///
    /// <para><see cref="Id"/>, <see cref="Title"/>, <see cref="Summary"/> and
    /// <see cref="Category"/> are required by the authoring contract, so they are
    /// filled on every article the loader admits (an entry with no <c>id</c> is
    /// skipped outright). Everything else is optional and has a <c>Has*</c>
    /// companion.</para>
    ///
    /// <para><b><see cref="Summary"/> is the one-sentence string, not an object.</b>
    /// <see cref="Article"/> deliberately has no summary-<i>object</i> property, so
    /// the name means the same thing on both types and never has to be disambiguated
    /// at a call site.</para>
    /// </summary>
    public sealed class ArticleSummary
    {
        /// <summary>
        /// Stable kebab-case ASCII key from front matter ("tubaroes-de-noronha") —
        /// the route payload and the only thing that identifies an article. A lookup
        /// key, never rendered. <b>Renaming one is a breaking change</b>: any link
        /// that carries it (a future deep link, a card the Início screen pins) stops
        /// resolving, so add an article rather than re-keying one.
        /// </summary>
        public string Id;

        /// <summary>Headline, pt-BR. Required; plain text, no inline tags.</summary>
        public string Title;

        /// <summary>One-sentence teaser under the headline. Required; plain text.</summary>
        public string Summary;

        /// <summary>
        /// Free pt-BR text the index groups by ("Espécies"). Required. It is
        /// <b>both</b> the grouping key and the visible heading — there is no
        /// separate machine key, so the author renaming a category renames the
        /// heading and re-groups the index in one edit, which is the intended
        /// lever. Compared exactly (trimmed), so "Espécies" and "espécies" are two
        /// groups.
        /// </summary>
        public string Category;

        /// <summary>Cover sprite path for <c>Resources.Load&lt;Sprite&gt;</c>, no
        /// extension ("Animals/tiger_shark"). Optional — an article with no hero
        /// draws a text-only card.</summary>
        public string HeroImage;

        /// <summary>Attribution for <see cref="HeroImage"/>. A licence condition
        /// wherever the photo is shown; never dimmed.</summary>
        public string HeroCredit;

        /// <summary>
        /// The author's ordering lever, ascending; ties break on title. Lower sorts
        /// first. <b>Absent in the JSON lands as 0 and therefore sorts first</b> —
        /// which is why the build script always writes an explicit default (1000)
        /// rather than omitting the field.
        /// </summary>
        public int Order;

        /// <summary>
        /// Last-edited date from front matter, or null when the author omitted it.
        ///
        /// <para><b>A calendar date, not an instant</b> — <c>DateTimeKind.Unspecified</c>
        /// on purpose. It says "this text was revised on the 29th", which is true in
        /// every timezone, so it must never be pushed through a UTC→local conversion:
        /// doing so would move a date across midnight for half the world and claim a
        /// revision that did not happen that day.</para>
        /// </summary>
        public DateTime? Updated;

        /// <summary>
        /// Words in the body, counted by the build script. The input to the reading
        /// estimate, never shown raw. 0 means "not counted / empty body", and
        /// <c>ArticleFormatter.ReadingTime</c> then returns null rather than printing
        /// "0 min" — a derived number must not assert something the data does not
        /// support.
        /// </summary>
        public int WordCount;

        public bool HasTitle => !string.IsNullOrWhiteSpace(Title);
        public bool HasSummary => !string.IsNullOrWhiteSpace(Summary);
        public bool HasCategory => !string.IsNullOrWhiteSpace(Category);
        public bool HasHeroImage => !string.IsNullOrWhiteSpace(HeroImage);
        public bool HasHeroCredit => !string.IsNullOrWhiteSpace(HeroCredit);
        public bool HasUpdated => Updated.HasValue;
        public bool HasWordCount => WordCount > 0;
    }

    /// <summary>
    /// One article, body included — what the reading screen binds to.
    ///
    /// <para><b>The identity fields are declared again rather than inherited</b>,
    /// because the contract fixes both this and <see cref="ArticleSummary"/> as
    /// sealed. That is not an oversight: an index row must not carry a parsed block
    /// list it will never draw, and a reading screen must not reach through a nested
    /// <c>Summary</c> object to print the title. <see cref="With"/> is the single
    /// place the two are copied across, so the duplication cannot drift field by
    /// field.</para>
    /// </summary>
    public sealed class Article
    {
        /// <inheritdoc cref="ArticleSummary.Id"/>
        public string Id;

        /// <inheritdoc cref="ArticleSummary.Title"/>
        public string Title;

        /// <summary>The one-sentence teaser — a string, exactly as on
        /// <see cref="ArticleSummary.Summary"/>. There is no summary-object property
        /// on this type, so the name is unambiguous.</summary>
        public string Summary;

        /// <inheritdoc cref="ArticleSummary.Category"/>
        public string Category;

        /// <inheritdoc cref="ArticleSummary.HeroImage"/>
        public string HeroImage;

        /// <inheritdoc cref="ArticleSummary.HeroCredit"/>
        public string HeroCredit;

        /// <inheritdoc cref="ArticleSummary.Order"/>
        public int Order;

        /// <inheritdoc cref="ArticleSummary.Updated"/>
        public DateTime? Updated;

        /// <inheritdoc cref="ArticleSummary.WordCount"/>
        public int WordCount;

        /// <summary>
        /// The body, in authoring order. Never null; an article with no body is
        /// legitimate (front matter alone) and renders as hero + title + summary.
        ///
        /// <para><b>This list is honest, not filtered</b> — it still contains blocks
        /// whose <see cref="ArticleBlock.IsRenderable"/> is false, including
        /// <see cref="ArticleBlockKind.Unknown"/> ones from a newer content file, so
        /// tooling can see them. Bind <c>ArticleViewModel.Blocks</c>, which applies
        /// the filter once, rather than filtering in a screen.</para>
        /// </summary>
        public IReadOnlyList<ArticleBlock> Blocks = Array.Empty<ArticleBlock>();

        public bool HasTitle => !string.IsNullOrWhiteSpace(Title);
        public bool HasSummary => !string.IsNullOrWhiteSpace(Summary);
        public bool HasCategory => !string.IsNullOrWhiteSpace(Category);
        public bool HasHeroImage => !string.IsNullOrWhiteSpace(HeroImage);
        public bool HasHeroCredit => !string.IsNullOrWhiteSpace(HeroCredit);
        public bool HasUpdated => Updated.HasValue;
        public bool HasWordCount => WordCount > 0;
        public bool HasBlocks => Blocks != null && Blocks.Count > 0;

        /// <summary>
        /// The article that <paramref name="summary"/> describes, carrying
        /// <paramref name="blocks"/>. The only place the two types' shared fields are
        /// copied — a field added to one belongs here in the same edit.
        /// </summary>
        public static Article With(ArticleSummary summary, IReadOnlyList<ArticleBlock> blocks)
        {
            if (summary == null) return null;
            return new Article
            {
                Id = summary.Id,
                Title = summary.Title,
                Summary = summary.Summary,
                Category = summary.Category,
                HeroImage = summary.HeroImage,
                HeroCredit = summary.HeroCredit,
                Order = summary.Order,
                Updated = summary.Updated,
                WordCount = summary.WordCount,
                Blocks = blocks ?? Array.Empty<ArticleBlock>(),
            };
        }

        /// <summary>The index-row view of this article. For tooling and tests; the
        /// index reads <c>IArticleCatalog.All()</c>, which never parses a body it is
        /// not going to show.</summary>
        public ArticleSummary ToSummary() => new ArticleSummary
        {
            Id = Id,
            Title = Title,
            Summary = Summary,
            Category = Category,
            HeroImage = HeroImage,
            HeroCredit = HeroCredit,
            Order = Order,
            Updated = Updated,
            WordCount = WordCount,
        };
    }

    /// <summary>
    /// Read-only access to the educational articles generated into
    /// <c>Assets/Resources/articles.json</c> by <c>tools/build_articles.py</c>.
    /// Implemented by <c>UiServiceAdapters.ArticleCatalogAdapter</c> over
    /// <c>ArticleLibrary</c>, which is the file reader.
    ///
    /// <para><b>Nothing here throws and nothing returns null where a list is
    /// expected</b> — the same contract <see cref="IBeachContent"/> sets. A missing
    /// file, malformed JSON, an entry with no id and an unknown block type are each
    /// logged once by the loader and degraded; the worst case is an empty catalog
    /// with <see cref="IsAvailable"/> false.</para>
    /// </summary>
    public interface IArticleCatalog
    {
        /// <summary>
        /// Every article's index row, in index order (<c>order</c> ascending, then
        /// title, then id so the order is total and therefore identical on every
        /// run). Never null; empty when nothing is authored <i>or</i> when the file
        /// could not be read — <see cref="IsAvailable"/> is what tells those apart.
        /// </summary>
        IReadOnlyList<ArticleSummary> All();

        /// <summary>
        /// The full article for an id, or <b>null</b> for an unknown or blank one. A
        /// null is the caller's cue not to navigate: an unknown id means a stale link
        /// or a typo in the content file, and a blank reading screen is worse than
        /// staying put.
        /// </summary>
        Article Find(string id);

        /// <summary>
        /// The catalog was readable. <b>False means the build is broken, not that the
        /// user is offline</b> — <c>articles.json</c> ships inside the APK, so there
        /// is no network in this path and no connectivity state to report. Screens use
        /// it only to choose between the "nothing authored yet" and the "could not
        /// load" copy; both are dead ends with no retry (see
        /// <see cref="StateViewCopy"/>).
        /// </summary>
        bool IsAvailable { get; }
    }
}
