#!/usr/bin/env python3
"""Generate Material Design 3 color tokens as USS variables for UI Toolkit.

This is the SINGLE SOURCE OF TRUTH for the app's color scheme. Never hand-edit
the generated _colors-*.uss files — rerun this script instead.

Two input modes:

1. Seed color (algorithmic, same HCT pipeline Material Theme Builder uses):
     .venv/bin/python generate_md3_tokens.py --seed "#00A0B0"
   Optional: --variant tonal_spot|vibrant|expressive|neutral|fidelity|content|monochrome
             --contrast 0.0   (range -1.0 .. 1.0, 0 = default)

2. Material Theme Builder JSON export (when the designer hands one over):
     .venv/bin/python generate_md3_tokens.py --from-json material-theme.json
   Reads schemes.light / schemes.dark from the export verbatim.

Output: Assets/DesignSystem/Tokens/_colors-light.uss and _colors-dark.uss,
each defining --md-sys-color-* variables on :root.

Setup (one-time):  python3 -m venv .venv && .venv/bin/pip install materialyoucolor
"""

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "src/app/MergulhoVirtual/Assets/DesignSystem/Tokens"
DEFAULT_SEED = "#00A0B0"  # Noronha ocean turquoise (placeholder until the designer picks)

# Internal palette-key roles are not part of the md.sys.color token set.
EXCLUDED_ROLES = re.compile(r"PaletteKeyColor$")


def camel_to_kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def hex_of(rgba) -> str:
    r, g, b, _ = rgba
    return f"#{r:02X}{g:02X}{b:02X}"


def scheme_from_seed(seed: str, variant: str, contrast: float, dark: bool, spec: str) -> dict:
    from materialyoucolor.dynamiccolor.dynamic_color import DynamicColor
    from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors
    from materialyoucolor.hct import Hct

    scheme_classes = {
        "tonal_spot": "materialyoucolor.scheme.scheme_tonal_spot.SchemeTonalSpot",
        "vibrant": "materialyoucolor.scheme.scheme_vibrant.SchemeVibrant",
        "expressive": "materialyoucolor.scheme.scheme_expressive.SchemeExpressive",
        "neutral": "materialyoucolor.scheme.scheme_neutral.SchemeNeutral",
        "fidelity": "materialyoucolor.scheme.scheme_fidelity.SchemeFidelity",
        "content": "materialyoucolor.scheme.scheme_content.SchemeContent",
        "monochrome": "materialyoucolor.scheme.scheme_monochrome.SchemeMonochrome",
    }
    module_path, class_name = scheme_classes[variant].rsplit(".", 1)
    module = __import__(module_path, fromlist=[class_name])
    scheme_cls = getattr(module, class_name)

    argb = int(seed.lstrip("#"), 16) | 0xFF000000
    scheme = scheme_cls(Hct.from_int(argb), dark, contrast, spec_version=spec)

    roles = {}
    for attr in dir(MaterialDynamicColors):
        color = getattr(MaterialDynamicColors, attr)
        if not isinstance(color, DynamicColor) or EXCLUDED_ROLES.search(attr):
            continue
        roles[camel_to_kebab(attr)] = hex_of(color.get_hct(scheme).to_rgba())
    return roles


def scheme_from_json(path: Path, dark: bool) -> dict:
    export = json.loads(path.read_text())
    key = "dark" if dark else "light"
    try:
        scheme = export["schemes"][key]
    except KeyError:
        sys.exit(f"error: {path} has no schemes.{key} — is this a Material Theme Builder export?")
    return {camel_to_kebab(role): value for role, value in scheme.items()}


def write_uss(out_dir: Path, theme: str, roles: dict, provenance: str) -> Path:
    lines = [
        f"/* GENERATED by tools/design_system/generate_md3_tokens.py — DO NOT HAND-EDIT.",
        f" * Regenerate: .venv/bin/python tools/design_system/generate_md3_tokens.py {provenance}",
        f" * Theme: {theme} · Generated: {date.today().isoformat()}",
        f" */",
        ":root {",
    ]
    lines += [f"    --md-sys-color-{name}: {value};" for name, value in sorted(roles.items())]
    # Derived alpha tokens: USS has no color-mix(), so M3's alpha-composited
    # disabled colors (content 38%, container/outline 12% of on-surface) are
    # emitted as concrete rgba() values here.
    r, g, b = (int(roles["on-surface"][i:i + 2], 16) for i in (1, 3, 5))
    lines += [
        f"    --md-sys-color-on-surface-disabled-content: rgba({r}, {g}, {b}, 0.38);",
        f"    --md-sys-color-on-surface-disabled-container: rgba({r}, {g}, {b}, 0.12);",
    ]
    lines.append("}")
    out = out_dir / f"_colors-{theme}.uss"
    out.write_text("\n".join(lines) + "\n")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seed", default=DEFAULT_SEED, help=f"seed color hex (default {DEFAULT_SEED})")
    parser.add_argument("--variant", default="tonal_spot", choices=[
        "tonal_spot", "vibrant", "expressive", "neutral", "fidelity", "content", "monochrome"])
    parser.add_argument("--contrast", type=float, default=0.0, help="-1.0 .. 1.0 (default 0)")
    parser.add_argument("--spec", default="2021", choices=["2021", "2025"],
                        help="M3 token spec: 2021 = classic (matches m3.material.io docs and "
                             "Theme Builder exports), 2025 = M3 Expressive (default 2021)")
    parser.add_argument("--from-json", type=Path, default=None,
                        help="Material Theme Builder JSON export (overrides --seed)")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    for theme, dark in (("light", False), ("dark", True)):
        if args.from_json:
            roles = scheme_from_json(args.from_json, dark)
            provenance = f"--from-json {args.from_json.name}"
        else:
            roles = scheme_from_seed(args.seed, args.variant, args.contrast, dark, args.spec)
            provenance = (f"--seed \"{args.seed}\" --variant {args.variant} "
                          f"--contrast {args.contrast} --spec {args.spec}")
        path = write_uss(args.out, theme, roles, provenance)
        print(f"wrote {path.relative_to(REPO_ROOT)} ({len(roles)} roles)")


if __name__ == "__main__":
    main()
