#!/usr/bin/env python3
"""Subset the Material Symbols variable font to the icons the app actually uses.

Reads the icon list from material_symbols_icons.txt, resolves codepoints from
the official .codepoints file, pins the variable axes to the outlined default
(FILL=0, GRAD=0, opsz=24, wght=400), and writes:

  - Assets/DesignSystem/Fonts/MaterialSymbols.ttf   (the shipped subset font)
  - Assets/DesignSystem/Components/MdIcon/MdIconGlyphs.gen.cs  (name -> glyph map)

Adding an icon = add its name to material_symbols_icons.txt, rerun this script,
then rerun the font-asset generation (make ds-setup).

Source files (fonts_src/) are downloaded once from google/material-design-icons;
rerun the curl commands in tools/design_system/README.md if they're missing.
"""

import sys
from datetime import date
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
SRC_FONT = HERE / "fonts_src/MaterialSymbolsOutlined.ttf"
SRC_CODEPOINTS = HERE / "fonts_src/MaterialSymbolsOutlined.codepoints"
ICON_LIST = HERE / "material_symbols_icons.txt"
OUT_FONT = REPO_ROOT / "src/app/MergulhoVirtual/Assets/DesignSystem/Fonts/MaterialSymbols.ttf"
OUT_CS = REPO_ROOT / "src/app/MergulhoVirtual/Assets/DesignSystem/Components/MdIcon/MdIconGlyphs.gen.cs"

AXIS_PINS = {"FILL": 0, "GRAD": 0, "opsz": 24, "wght": 400}


def read_icons() -> list[str]:
    icons = []
    for line in ICON_LIST.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            icons.append(line)
    return sorted(set(icons))


def read_codepoints() -> dict[str, int]:
    table = {}
    for line in SRC_CODEPOINTS.read_text().splitlines():
        name, _, hexcode = line.strip().partition(" ")
        if name and hexcode:
            table[name] = int(hexcode, 16)
    return table


def main() -> None:
    for f in (SRC_FONT, SRC_CODEPOINTS):
        if not f.exists():
            sys.exit(f"error: {f} missing — see tools/design_system/README.md for download steps")

    icons = read_icons()
    table = read_codepoints()
    missing = [i for i in icons if i not in table]
    if missing:
        sys.exit(f"error: not in codepoints file (typo?): {', '.join(missing)}")
    selected = {name: table[name] for name in icons}

    font = TTFont(SRC_FONT)
    instantiateVariableFont(font, AXIS_PINS, inplace=True)

    options = subset.Options()
    options.layout_features = []          # icons need no OpenType features
    options.name_IDs = [1, 2, 3, 4, 6]    # keep basic naming records
    options.notdef_outline = True
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=list(selected.values()))
    subsetter.subset(font)

    OUT_FONT.parent.mkdir(parents=True, exist_ok=True)
    font.save(OUT_FONT)

    lines = [
        "// GENERATED by tools/design_system/subset_material_symbols.py — DO NOT HAND-EDIT.",
        "// Icon set: tools/design_system/material_symbols_icons.txt "
        f"({len(selected)} icons, generated {date.today().isoformat()}).",
        "using System.Collections.Generic;",
        "",
        "namespace MergulhoVirtual.DesignSystem",
        "{",
        "    /// <summary>Icon name → Material Symbols glyph for the shipped subset font.</summary>",
        "    public static class MdIconGlyphs",
        "    {",
        "        public static readonly IReadOnlyDictionary<string, string> Map =",
        "            new Dictionary<string, string>",
        "        {",
    ]
    for name, cp in selected.items():
        lines.append(f"            {{ \"{name}\", \"\\U{cp:08X}\" }},")
    lines += [
        "        };",
        "    }",
        "}",
        "",
    ]
    OUT_CS.parent.mkdir(parents=True, exist_ok=True)
    OUT_CS.write_text("\n".join(lines))

    size_kb = OUT_FONT.stat().st_size / 1024
    print(f"wrote {OUT_FONT.relative_to(REPO_ROOT)} ({size_kb:.0f} KB, {len(selected)} icons)")
    print(f"wrote {OUT_CS.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
