using UnityEngine.UIElements;
#if UNITY_STANDALONE && !UNITY_EDITOR
using UnityEngine;
using UnityEngine.InputSystem;
#endif

/// <summary>
/// Letterboxes the UI Toolkit shell into a selectable phone-sized frame, for the
/// throwaway Windows review build only (docs/windows-review-build.md, Steps 1,
/// 1b and 1c). Not a supported platform: nothing here runs on Android or in the
/// editor, and none of it should outlive the review target.
///
/// <para><b>Why it exists.</b> AppPanelSettings uses Constant Physical Size at
/// 160 dpi, which is exactly what gives <c>1 USS px = 1 dp = 1 Figma pt</c> on a
/// phone — and is actively wrong on a desktop, where the panel would scale by the
/// monitor's DPI (~0.6x on a 1080p screen, something else on a HiDPI laptop). So
/// the desktop build switches the panel to Constant Pixel Size and derives the
/// scale from the window instead, then pins the router to an explicit dp frame
/// the designer can switch between. The area around the frame is bezel.</para>
///
/// <para><b>The <c>!UNITY_EDITOR</c> half of the guard is load-bearing.</b>
/// UNITY_STANDALONE is also defined in the Linux editor, and PanelSettings is a
/// ScriptableObject — an Editor-time write to <c>scaleMode</c>/<c>scale</c> would
/// be serialized back into AppPanelSettings.asset and silently break the mobile
/// 160-dpi calibration for everyone (and the asset is generated by AppUiBuilder,
/// so the damage would survive until someone re-ran `make ui-setup`). Never drop
/// the <c>!UNITY_EDITOR</c> to "test it in the editor" — use `make ds-shots`,
/// which parameterizes the same frame without touching the asset.</para>
/// </summary>
public static class DesktopReviewMode
{
    /// <summary>
    /// A device the designer can switch to. Frame size AND safe-area insets
    /// travel together, because the insets are a property of the device and not
    /// a constant: a notched iPhone is 47/34, a typical Android is ~24 top and
    /// <b>0</b> bottom (the gesture bar is an overlay, not a reserved strip).
    /// Shipping one inset pair across all presets would make the Android frames
    /// silently wrong — and "does the nav bar look right on Android" is one of
    /// the questions this build exists to answer.
    /// </summary>
    public readonly struct Preset
    {
        public readonly string Label;
        public readonly int W, H;
        public readonly float Top, Bottom;

        public Preset(string label, int w, int h, float top, float bottom)
        {
            Label = label;
            W = w;
            H = h;
            Top = top;
            Bottom = bottom;
        }
    }

    /// <summary>
    /// The review matrix. 47/34 on the reference frame is the same pair
    /// UiScreenshotHarness injects, so the exe and <c>.shots/</c> agree. Every
    /// preset is portrait because the app is portrait-locked
    /// (docs/android-adaptivity.md), not by omission.
    /// </summary>
    public static readonly Preset[] Presets =
    {
        new Preset("Android 360×640", 360, 640, 24f, 0f),  // small 16:9 — the stress test
        new Preset("Android 360×800", 360, 800, 24f, 0f),  // most common budget device
        new Preset("V2 ref 390×844",  390, 844, 47f, 34f), // what everything was designed at
        new Preset("Pixel 412×915",   412, 915, 24f, 0f),
        new Preset("iPhone 430×932",  430, 932, 47f, 34f),
    };

    /// <summary>Index into <see cref="Presets"/>; starts on the V2 reference frame.</summary>
    static int current = 2;

    /// <summary>
    /// The active device. Read outside the guard as well — AppUiHost.ApplyEdgeInsets
    /// takes its insets from here on desktop, and a property that only exists on one
    /// platform would make that call site need its own #if.
    /// </summary>
    public static Preset Current => Presets[current];

    // ---- Entry points (present on every platform; no-ops off desktop) --------

    /// <summary>
    /// Switches the panel to Constant Pixel Size, centres the router inside a
    /// bezel, and starts the hotkey picker. Call from
    /// <c>AppUiHost.OnEnable</c> after the router has been added to the panel
    /// root — NOT from Awake: UIDocument tears the visual tree down on deactivate
    /// and rebuilds it, so a root captured in Awake is stale by the time the
    /// panel renders.
    /// </summary>
    /// <param name="panel">The UIDocument's PanelSettings (mutated at runtime only).</param>
    /// <param name="documentRoot">The panel root — becomes the bezel.</param>
    /// <param name="routerRoot">The MdRouter — becomes the device frame.</param>
    public static void Apply(PanelSettings panel, VisualElement documentRoot, VisualElement routerRoot)
    {
#if UNITY_STANDALONE && !UNITY_EDITOR
        if (panel == null || documentRoot == null || routerRoot == null) return;

        activePanel = panel;
        activeRoot = documentRoot;
        activeFrame = routerRoot;
        appliedScale = float.NaN;

        // 1 USS px now maps to a known number of screen px (Refit picks the
        // number) instead of to whatever DPI the designer's monitor reports.
        panel.scaleMode = PanelScaleMode.ConstantPixelSize;

        // The frame is centred in whatever window the user drags out; everything
        // around it is bezel, painted flat so the frame edge is unambiguous.
        documentRoot.style.justifyContent = Justify.Center;
        documentRoot.style.alignItems = Align.Center;
        documentRoot.style.backgroundColor = (Color)new Color32(0x2A, 0x2A, 0x2A, 0xFF);

        // MdRouter's constructor sets flexGrow: 1 so the shell fills a phone
        // screen. Here it must be exactly the preset's dp size instead.
        routerRoot.style.flexGrow = 0f;
        routerRoot.style.flexShrink = 0f;

        EnsureHud(documentRoot);
        // UIDocument rebuilds the tree on every enable, but rootVisualElement
        // itself survives — so unregister first or the callbacks stack up.
        documentRoot.UnregisterCallback<GeometryChangedEvent>(OnRootGeometryChanged);
        documentRoot.RegisterCallback<GeometryChangedEvent>(OnRootGeometryChanged);
        Select(current);
#endif
    }

    /// <summary>
    /// One frame of the device picker: F2 = previous preset, F3 = next, digits
    /// 1-5 jump straight to one. Polled from <c>AppUiHost.Update</c>.
    ///
    /// <para>Uses <see cref="UnityEngine.InputSystem.Keyboard"/> rather than
    /// <c>Input.GetKeyDown</c>: the project is <c>activeInputHandler: 1</c> (new
    /// Input System only), where the legacy API throws at runtime.</para>
    /// </summary>
    public static void PollHotkeys()
    {
#if UNITY_STANDALONE && !UNITY_EDITOR
        if (activePanel == null) return;
        var kb = Keyboard.current;
        if (kb == null) return;

        if (kb.f2Key.wasPressedThisFrame) { Select(current - 1); return; }
        if (kb.f3Key.wasPressedThisFrame) { Select(current + 1); return; }

        // Key.Digit1..Digit9 are contiguous, so the nth preset is the nth digit.
        for (int i = 0; i < Presets.Length && i < 9; i++)
        {
            if (kb[(Key)((int)Key.Digit1 + i)].wasPressedThisFrame) { Select(i); return; }
        }
#endif
    }

    // ---- Desktop-only internals ---------------------------------------------

#if UNITY_STANDALONE && !UNITY_EDITOR
    /// <summary>Smallest scale we will letterbox at; below this the frame is
    /// unreadable and the honest answer is "make the window bigger".</summary>
    const float MinScale = 0.5f;

    static PanelSettings activePanel;
    static VisualElement activeRoot;
    static VisualElement activeFrame;
    static Label hud;
    static float appliedScale = float.NaN;

    /// <summary>
    /// Makes <paramref name="index"/> the active device (wrapping in both
    /// directions), resizes the frame, refits the scale and pushes the preset's
    /// insets through the router.
    /// </summary>
    public static void Select(int index)
    {
        current = ((index % Presets.Length) + Presets.Length) % Presets.Length;

        if (activeFrame != null)
        {
            activeFrame.style.width = (float)Current.W;
            activeFrame.style.height = (float)Current.H;
        }
        Refit();
        UpdateHud();

        // Insets go through the same seam UiScreenshotHarness uses. AppUiHost.Router
        // is an instance property, so this has to come off the singleton — and it is
        // null between OnDisable and the next OnEnable, which the ?. covers.
        AppUiHost.Instance?.Router?.SetEdgeInsets(Current.Top, 0f, 0f, Current.Bottom);
    }

    static void OnRootGeometryChanged(GeometryChangedEvent _)
    {
        Refit();
        UpdateHud();
    }

    /// <summary>
    /// Picks the largest panel scale at which the whole frame still fits in the
    /// window, snapped to quarter steps.
    ///
    /// <para>The quarter-step snap is not cosmetic. The design system draws every
    /// elevated surface as a 1px <c>outline-variant</c> border rather than a
    /// shadow (UI Toolkit has no box-shadow), and at an arbitrary fractional
    /// scale those hairlines land on fractional device pixels and render
    /// inconsistently — some 1px, some 2px, some a washed-out grey. Text is
    /// unaffected (SDF). Do not "improve" this by using the raw ratio.</para>
    /// </summary>
    static void Refit()
    {
        if (activePanel == null) return;

        float fit = Mathf.Min(Screen.width / (float)Current.W,
                              Screen.height / (float)Current.H);
        float scale = Mathf.Max(MinScale, Mathf.Floor(fit * 4f) / 4f);

        // Writing the same value back would dirty the panel and re-fire the
        // geometry callback that called us — assign only on a real change.
        if (Mathf.Approximately(scale, appliedScale)) return;
        appliedScale = scale;
        activePanel.scale = scale;
    }

    /// <summary>
    /// The always-on preset readout. It lives in the BEZEL, never inside the
    /// frame, so a screenshot the designer sends back is self-identifying without
    /// the picker ever being mistaken for app chrome.
    /// </summary>
    static void EnsureHud(VisualElement documentRoot)
    {
        hud = new Label { name = "desktop-review-hud", pickingMode = PickingMode.Ignore };
        hud.style.position = Position.Absolute;
        hud.style.left = 0f;
        hud.style.right = 0f;
        hud.style.unityTextAlign = TextAnchor.MiddleCenter;
        hud.style.fontSize = 12f;
        hud.style.color = new Color(0.90f, 0.90f, 0.90f, 1f); // readable on #2A2A2A
        documentRoot.Add(hud);
    }

    static void UpdateHud()
    {
        if (hud == null || activeRoot == null) return;
        hud.text = Current.Label + "  ·  F2/F3";

        // Park it in the bezel band below the frame. Both are in panel units, so
        // the root's own resolved height is the window height already divided by
        // the panel scale — no second conversion. If the window is barely taller
        // than the frame there is no band to sit in and the label clamps to the
        // bottom edge; that overlap is the cue to make the window bigger.
        float rootHeight = activeRoot.resolvedStyle.height;
        if (float.IsNaN(rootHeight) || rootHeight <= 0f) return;
        float frameBottom = (rootHeight + Current.H) * 0.5f;
        hud.style.top = Mathf.Min(frameBottom + 4f, rootHeight - 18f);
    }
#endif
}
