using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using MergulhoVirtual.UI;
using UnityEngine;

/// <summary>
/// Adapters that hand the existing Assembly-CSharp services to the
/// MergulhoVirtual.UI layer through its engine-free interfaces. This is the
/// only place that maps ConditionsSnapshot/TideSnapshot/PlaceData to the UI
/// layer's ConditionsData/TideData/BeachInfo — keep the mapping here, not in
/// the ViewModels.
/// </summary>
public static class UiServiceAdapters
{
    public sealed class BeachCatalogAdapter : IBeachCatalog
    {
        List<BeachInfo> beaches;

        public IReadOnlyList<BeachInfo> Beaches
        {
            get
            {
                if (beaches == null)
                {
                    beaches = new List<BeachInfo>();
                    foreach (var place in ReverseGeocoding.GetAllPlaces())
                    {
                        if (place == null || string.IsNullOrEmpty(place.name)) continue;
                        beaches.Add(new BeachInfo
                        {
                            // Key stays the places.json `name` (spawner / content
                            // file / backend `local` all agree on it); the label is
                            // the pt-BR displayName, which BeachInfo falls back from
                            // when an older places.json has none.
                            Name = place.name,
                            DisplayName = place.displayName,
                            ImageName = place.imageName,
                            Description = place.description,
                            PhotoCredit = place.photoCredit,
                        });
                    }
                }
                return beaches;
            }
        }
    }

    /// <summary>
    /// The hand-authored per-beach content, read by <see cref="BeachContentLibrary"/>
    /// from Resources/beaches_content.json. Stateless and cheap to construct — the
    /// parsed file is cached process-wide by the library.
    ///
    /// <para><see cref="ForBeach"/> never returns null: an unknown beach, an
    /// unreadable file and an all-blank entry all come back as an empty
    /// <see cref="BeachContent"/>, so screens bind unconditionally and hide the
    /// sections whose Has* flag is false.</para>
    /// </summary>
    public sealed class BeachContentAdapter : IBeachContent
    {
        public BeachContent ForBeach(string beachName) =>
            BeachContentLibrary.Find(beachName) ?? BeachContent.EmptyFor(beachName);

        public bool TryGetContent(string beachName, out BeachContent content)
        {
            content = BeachContentLibrary.Find(beachName);
            if (content != null) return true;
            content = BeachContent.EmptyFor(beachName);
            return false;
        }
    }

    /// <summary>
    /// The educational articles, read by <see cref="ArticleLibrary"/> from
    /// Resources/articles.json (generated by <c>tools/build_articles.py</c> from
    /// content/articles/*.md). Stateless and cheap to construct — the parsed file is
    /// cached process-wide by the library, exactly like
    /// <see cref="BeachContentAdapter"/>.
    ///
    /// <para><see cref="All"/> never returns null and is already in index order
    /// (<c>order</c> asc, then title, then id). <see cref="Find"/> returns null for an
    /// unknown id, which is the caller's cue not to navigate.
    /// <see cref="IsAvailable"/> is false only when the file was missing or unreadable
    /// — <b>never a connectivity state</b>: articles.json ships inside the APK, so
    /// there is no network anywhere in this path.</para>
    /// </summary>
    public sealed class ArticleCatalogAdapter : IArticleCatalog
    {
        public IReadOnlyList<ArticleSummary> All() => ArticleLibrary.All();

        public Article Find(string id) => ArticleLibrary.Find(id);

        public bool IsAvailable => ArticleLibrary.IsAvailable;
    }

    /// <summary>
    /// The species catalog over the AnimalDef ScriptableObjects in
    /// Resources/Animals — the same assets the Animais screen lists, so the beach
    /// species chips, the 3D catalog and (Slice 4) the AR card cannot drift into
    /// three spellings of the same animal.
    ///
    /// <para>Keyed by the asset file name ("lemon_shark"), which is what
    /// beaches_content.json writes. <c>Resources.LoadAll</c> runs once, lazily, on
    /// first use.</para>
    /// </summary>
    public sealed class SpeciesCatalogAdapter : ISpeciesCatalog
    {
        List<SpeciesInfo> species;
        Dictionary<string, SpeciesInfo> byKey;

        public IReadOnlyList<SpeciesInfo> Species
        {
            get
            {
                EnsureLoaded();
                return species;
            }
        }

        public SpeciesInfo Find(string key)
        {
            if (string.IsNullOrEmpty(key)) return null;
            EnsureLoaded();
            return byKey.TryGetValue(key, out var info) ? info : null;
        }

        void EnsureLoaded()
        {
            if (species != null) return;
            species = new List<SpeciesInfo>();
            byKey = new Dictionary<string, SpeciesInfo>(StringComparer.Ordinal);

            foreach (var animal in Resources.LoadAll<AnimalDef>("Animals"))
            {
                if (animal == null || string.IsNullOrEmpty(animal.name)) continue;
                var info = new SpeciesInfo
                {
                    // Asset file name is the key; displayName is the only label.
                    Key = animal.name,
                    DisplayName = string.IsNullOrWhiteSpace(animal.displayName)
                        ? animal.name
                        : animal.displayName,
                    Binomial = animal.binomial,
                    ImageName = animal.imageName,
                    Description = animal.description,
                    // The AR species card's three spec rows (§8.4). Blank on every
                    // shipped asset by design (D8) — the card drops the rows it has
                    // no value for rather than inventing marine biology.
                    ApproximateSize = animal.approximateSize,
                    Diet = animal.diet,
                    Behaviour = animal.behaviour,
                    // Espécie screen (Decision D1). Credits are a licence condition
                    // on every shipped photo and model, not decoration.
                    PhotoCredit = animal.photoCredit,
                    ModelCredit = animal.modelCredit,
                    // The prefab itself is a GameObject and cannot cross into the UI
                    // assembly, so only its PRESENCE does; the model is reached by key
                    // through ISpeciesModelViewer. False here is a real state, and the
                    // usual cause is a dangling reference after the species' FBX was
                    // replaced (CLAUDE.md, "Replacing an existing species' FBX").
                    HasModel = animal.prefab != null,
                    Videos = MapVideos(animal),
                };
                if (byKey.ContainsKey(info.Key))
                {
                    Debug.LogWarning($"[SpeciesCatalog] Duplicate AnimalDef key \"{info.Key}\" — keeping the first.");
                    continue;
                }
                byKey[info.Key] = info;
                species.Add(info);
            }
        }

        /// <summary>
        /// AnimalDef.videos (a global <c>VideoRef[]</c>) to the UI layer's engine-free
        /// mirror. A clip with no URL is dropped rather than carried through to a card
        /// that cannot play — the only honest reading of an empty url field.
        /// </summary>
        static IReadOnlyList<SpeciesVideo> MapVideos(AnimalDef animal)
        {
            if (animal.videos == null || animal.videos.Length == 0) return Array.Empty<SpeciesVideo>();
            var list = new List<SpeciesVideo>(animal.videos.Length);
            foreach (var video in animal.videos)
            {
                if (video == null || string.IsNullOrWhiteSpace(video.url)) continue;
                list.Add(new SpeciesVideo(video.title, video.url));
            }
            return list;
        }
    }

    /// <summary>
    /// <see cref="IConnectivity"/> over <c>Application.internetReachability</c>.
    ///
    /// <para>Stateless and unsubscribed on purpose: Unity raises no reachability
    /// event, so the value is only ever read. It answers "is a link attached", not
    /// "can we reach the backend" — see the interface for what the callers may
    /// therefore claim.</para>
    /// </summary>
    public sealed class ConnectivityAdapter : IConnectivity
    {
        public bool IsOnline => Application.internetReachability != NetworkReachability.NotReachable;
    }

    public sealed class ConditionsServiceAdapter : IConditionsService, IDisposable
    {
        readonly ConditionsService service;

        public ConditionsData Current => Map(service != null ? service.CurrentConditions : null);

        /// <summary>No service wired = nothing has failed; the screen then shows the
        /// ordinary "—" rows rather than claiming an error it cannot have had.</summary>
        public bool LastFetchFailed => service != null && service.LastFetchFailed;

        public bool IsFetching => service != null && service.IsFetching;

        public void Refresh() => service?.Refresh();

        public event Action<ConditionsData> Changed;

        public ConditionsServiceAdapter(ConditionsService service)
        {
            this.service = service;
            if (service != null)
            {
                service.ConditionsChanged += OnChanged;
                service.FetchStateChanged += OnFetchStateChanged;
            }
        }

        public void Dispose()
        {
            if (service != null)
            {
                service.ConditionsChanged -= OnChanged;
                service.FetchStateChanged -= OnFetchStateChanged;
            }
        }

        void OnChanged(ConditionsSnapshot snap) => Changed?.Invoke(Map(snap));

        /// <summary>A fetch starting, failing or recovering changes what the card
        /// must draw even though no new snapshot arrived, so it comes out of the
        /// same event — the UI layer has one "re-render" signal, not two.</summary>
        void OnFetchStateChanged() => Changed?.Invoke(Current);

        static ConditionsData Map(ConditionsSnapshot s)
        {
            if (s == null) return null;
            return new ConditionsData
            {
                BeachName = s.beachName,
                FetchedAtUtc = s.fetchedAtTicksUtc > 0 ? s.FetchedAtUtc : DateTime.MinValue,
                WaveHeightM = s.WaveHeightM,
                WavePeriodS = s.WavePeriodS,
                WaveDirectionDeg = s.WaveDirectionDeg,
                SeaTempC = s.SeaTempC,
                WindSpeedKmh = s.WindSpeedKmh,
                WindDirectionDeg = s.WindDirectionDeg,
            };
        }
    }

    public sealed class TideServiceAdapter : ITideService, IDisposable
    {
        readonly TideService service;

        public TideData Current => Map(service != null ? service.CurrentTide : default);
        public event Action<TideData> Changed;

        public TideServiceAdapter(TideService service)
        {
            this.service = service;
            if (service != null) service.TideChanged += OnChanged;
        }

        public void Dispose()
        {
            if (service != null) service.TideChanged -= OnChanged;
        }

        void OnChanged(TideSnapshot snap) => Changed?.Invoke(Map(snap));

        static TideData Map(TideSnapshot t) => new TideData
        {
            Valid = t.valid,
            CurrentHeightM = t.currentHeightM,
            Rising = t.rising,
            NextHighAtUtc = t.nextHighAt,
            NextHighM = t.nextHighM,
            NextLowAtUtc = t.nextLowAt,
            NextLowM = t.nextLowM,
            Next24hHeights = t.next24hHeights,
            WindowStartUtc = t.windowStart,
        };
    }

    public sealed class BeachOverrideAdapter : IBeachOverride
    {
        readonly GPSHandler gps;

        public BeachOverrideAdapter(GPSHandler gps) => this.gps = gps;

        public void SetOverride(string beachName)
        {
            if (gps != null) gps.SetBeachOverride(beachName);
        }

        public void ClearOverride()
        {
            if (gps != null) gps.ClearBeachOverride();
        }
    }

    /// <summary>
    /// The read side of the same state <see cref="BeachOverrideAdapter"/> writes:
    /// whichever beach <c>GPSHandler</c> currently reports, which is the GPS
    /// resolution or the manual override when one is set (SetBeachOverride emits
    /// through the same PlaceChanged event, so one subscription covers both).
    ///
    /// <para>Deliberately NOT sourced from <c>ConditionsService</c>, which falls
    /// back to a default beach when GPS has nothing — fine for fetching a
    /// forecast, a lie under the words "você está em". A null key here is the
    /// honest, common answer and the Praias landing has a state for it.</para>
    /// </summary>
    /// <summary>
    /// The AR tap source (<see cref="ObjectInteraction"/>) behind the UI layer's
    /// <see cref="IArSelection"/> — Slice 4's whole assembly-boundary crossing for
    /// the AR HUD. Everything AR stays on this side; a species key goes across.
    ///
    /// <para>Null-tolerant like the other adapters: with no ObjectInteraction in
    /// the scene the event simply never fires and the screen shows a bare HUD, the
    /// way a missing GPSHandler leaves the beach selector inert rather than
    /// throwing at the composition root.</para>
    /// </summary>
    public sealed class ArSelectionAdapter : IArSelection, IDisposable
    {
        readonly ObjectInteraction source;

        public ArSelectionAdapter(ObjectInteraction source)
        {
            this.source = source;
            if (source != null) source.SpeciesSelected += OnSpeciesSelected;
        }

        public event Action<string> SpeciesSelected;

        public void SetListening(bool listening)
        {
            if (source != null) source.Listening = listening;
        }

        public void Dispose()
        {
            if (source == null) return;
            source.SpeciesSelected -= OnSpeciesSelected;
            source.Listening = false;
        }

        void OnSpeciesSelected(string speciesKey) => SpeciesSelected?.Invoke(speciesKey);
    }

    public sealed class ActiveBeachAdapter : IActiveBeach, IDisposable
    {
        readonly GPSHandler gps;

        public ActiveBeachAdapter(GPSHandler gps)
        {
            this.gps = gps;
            if (gps != null) gps.PlaceChanged += OnPlaceChanged;
        }

        public string ActiveBeachKey => gps != null ? gps.CurrentPlaceName : null;

        public event Action<string> ActiveBeachChanged;

        public void Dispose()
        {
            if (gps != null) gps.PlaceChanged -= OnPlaceChanged;
        }

        void OnPlaceChanged(string beachName) => ActiveBeachChanged?.Invoke(beachName);
    }

    /// <summary>
    /// First-run state over PlayerPrefs. Trivial on purpose: the UI layer must
    /// stay engine-free, so this is the whole of the persistence seam — one int
    /// per flag, keyed by <see cref="OnboardingPrefKeys"/> so the string is
    /// spelled in exactly one place.
    ///
    /// <para><c>Save()</c> is explicit because Unity only flushes PlayerPrefs on
    /// a clean quit: without it, dismissing the welcome card and then killing the
    /// app (or letting Android reclaim it) brings the card back.</para>
    /// </summary>
    public sealed class OnboardingStateAdapter : IOnboardingState
    {
        public bool WelcomeDismissed =>
            PlayerPrefs.GetInt(OnboardingPrefKeys.WelcomeDismissed, 0) != 0;

        public void DismissWelcome()
        {
            PlayerPrefs.SetInt(OnboardingPrefKeys.WelcomeDismissed, 1);
            PlayerPrefs.Save();
        }
    }

    /// <summary>
    /// The user's own sighting reports, over the Assembly-CSharp
    /// <see cref="JobQueue"/> — submit one, and read back the ones still in
    /// flight for the "Seus avistamentos pendentes" feed.
    ///
    /// <para><b>It owns the photo file.</b> The picker hands back a path in the
    /// app's cache (Android may evict it; iOS exported a temporary) and the user
    /// can delete the original from their gallery at any moment, so
    /// <see cref="Submit"/> copies the bytes into
    /// <c>persistentDataPath/sightings/&lt;guid&gt;.&lt;ext&gt;</c> before
    /// queueing and the job deletes that copy on success. The copy is
    /// <see cref="File.Copy"/> — raw bytes, never decode/re-encode — because EXIF
    /// (GPS, DateTimeOriginal, camera) is the point of the photo path.</para>
    ///
    /// <para><b>The guid is the idempotency key</b>, baked into both the file name
    /// and the job, so a retry after a TCP timeout the server already honoured
    /// collapses server-side instead of creating a second document.</para>
    ///
    /// <para>Constructing this also spins up the queue
    /// (<see cref="JobQueue.GetOrCreate"/>) and loads what is on disk. That is
    /// load-bearing, not incidental: nothing else in the scene instantiates the
    /// queue, so without it a sighting left queued by a previous run would never
    /// resume <i>and</i> would be missing from the feed.</para>
    /// </summary>
    public sealed class SightingReportsAdapter : ISightingReports, IDisposable
    {
        /// <summary>Prod endpoint (CLAUDE.md, "Updating Unity URLs for prod").
        /// Point the constructor at a LAN <c>BACKEND_DEBUG=1</c> backend for
        /// editor testing — that mode ignores the missing App Check header.</summary>
        public const string DefaultUploadUrl = "https://mergulhovirtual.dev/api/v1/avistamentos";

        readonly string uploadUrl;
        readonly JobQueue queue;

        public event Action Changed;

        public SightingReportsAdapter(string uploadUrl = null)
        {
            this.uploadUrl = string.IsNullOrWhiteSpace(uploadUrl) ? DefaultUploadUrl : uploadUrl;
            queue = JobQueue.GetOrCreate();
            // GetOrCreate's Start() loads from disk a frame later; do it now so the
            // very first render of the feed is right.
            queue.LoadPendingFromDisk();
            queue.JobCompleted += OnJobCompleted;
        }

        public void Dispose()
        {
            if (queue != null) queue.JobCompleted -= OnJobCompleted;
        }

        void OnJobCompleted(string jobId, JobResult result) => Changed?.Invoke();

        public bool Submit(SightingDraft draft)
        {
            if (draft == null) return false;
            if (string.IsNullOrEmpty(draft.PhotoPath) || !File.Exists(draft.PhotoPath))
            {
                Debug.LogWarning("[SightingReports] Submit called with no readable photo — dropping.");
                return false;
            }

            string ext = Path.GetExtension(draft.PhotoPath);
            if (string.IsNullOrEmpty(ext)) ext = ".jpg";

            string sightingId = Guid.NewGuid().ToString("N");
            string destDir = Path.Combine(Application.persistentDataPath, "sightings");
            string destPath = Path.Combine(destDir, sightingId + ext);

            try
            {
                Directory.CreateDirectory(destDir);
                File.Copy(draft.PhotoPath, destPath, overwrite: true);
            }
            catch (Exception e)
            {
                Debug.LogError($"[SightingReports] Could not copy the photo: {e.Message}");
                return false;
            }

            var job = new ReportSightingJob
            {
                Url = uploadUrl,
                ImagePath = destPath,
                MimeType = GuessMime(ext),
                BeachName = draft.BeachKey,
                IsoTimestamp = ToIsoUtc(draft.WhenUtc),
                SpeciesGuess = draft.SpeciesLabel,
                Notes = draft.Notes,
                IdempotencyKey = sightingId,
                SpeciesKey = draft.SpeciesKey,
                SizeBucket = draft.SizeBucket,
                Behaviours = ToArray(draft.BehaviourKeys),
                ReporterName = draft.ReporterName,
                ReporterEmail = draft.ReporterEmail,
                ReporterProfile = draft.ProfileKey,
            };

            if (!queue.Enqueue(job))
            {
                Debug.LogWarning("[SightingReports] Job queue full — sighting not taken.");
                try { File.Delete(destPath); } catch { /* best effort */ }
                return false;
            }

            Changed?.Invoke();
            return true;
        }

        /// <summary>
        /// Moves the report back from <c>jobs/failed/</c> into the queue. The
        /// <see cref="SightingRecord.Id"/> the feed shows is the job's idempotency
        /// key, which IS the job id today — but fall back to matching the failed
        /// list so the feed keeps working if that ever stops being true.
        /// </summary>
        public bool Retry(string id)
        {
            if (queue == null || string.IsNullOrEmpty(id)) return false;

            bool requeued = queue.Requeue(id);
            if (!requeued)
            {
                string jobId = FindFailedJobId(id);
                if (jobId != null && jobId != id) requeued = queue.Requeue(jobId);
            }
            if (requeued) Changed?.Invoke();
            return requeued;
        }

        /// <summary>Envelope id of the failed job whose idempotency key is
        /// <paramref name="id"/>, or null.</summary>
        string FindFailedJobId(string id)
        {
            var records = queue.ListFailed(ReportSightingJob.JobType);
            if (records == null) return null;
            foreach (var record in records)
            {
                var job = record.Snapshot<ReportSightingJob>();
                if (job != null && job.IdempotencyKey == id) return record.Id;
            }
            return null;
        }

        public IReadOnlyList<SightingRecord> ListPending() => Map(queue?.ListPending(ReportSightingJob.JobType));

        public IReadOnlyList<SightingRecord> ListFailed() => Map(queue?.ListFailed(ReportSightingJob.JobType));

        static IReadOnlyList<SightingRecord> Map(IReadOnlyList<JobRecord> records)
        {
            var list = new List<SightingRecord>();
            if (records == null) return list;
            foreach (var record in records)
            {
                var job = record.Snapshot<ReportSightingJob>();
                if (job == null) continue;
                list.Add(new SightingRecord
                {
                    // The idempotency key IS the job id today; fall back to the
                    // envelope id so a row always has a stable identity.
                    Id = string.IsNullOrEmpty(job.IdempotencyKey) ? record.Id : job.IdempotencyKey,
                    SpeciesKey = job.SpeciesKey,
                    SpeciesLabel = job.SpeciesGuess,
                    BeachKey = string.IsNullOrEmpty(job.BeachName) ? null : job.BeachName,
                    WhenUtc = ParseIsoUtc(job.IsoTimestamp, record.CreatedAtUtc),
                    PhotoPath = job.ImagePath,
                    State = MapState(record.State),
                    AttemptCount = record.AttemptCount,
                });
            }
            return list;
        }

        static SightingState MapState(JobRecordState state)
        {
            switch (state)
            {
                case JobRecordState.Retrying: return SightingState.Retrying;
                case JobRecordState.WaitingForNetwork: return SightingState.WaitingForNetwork;
                case JobRecordState.Failed: return SightingState.Failed;
                default: return SightingState.Queued;
            }
        }

        static string[] ToArray(IReadOnlyList<string> values)
        {
            if (values == null || values.Count == 0) return Array.Empty<string>();
            var array = new string[values.Count];
            for (int i = 0; i < values.Count; i++) array[i] = values[i];
            return array;
        }

        /// <summary>RFC3339 in UTC. An Unspecified kind is taken as already-UTC
        /// rather than converted from local — the draft field is named WhenUtc and
        /// a test clock that hands back an unspecified DateTime must not shift.</summary>
        static string ToIsoUtc(DateTime when)
        {
            DateTime utc = when.Kind == DateTimeKind.Unspecified
                ? DateTime.SpecifyKind(when, DateTimeKind.Utc)
                : when.ToUniversalTime();
            return utc.ToString("o", CultureInfo.InvariantCulture);
        }

        static DateTime ParseIsoUtc(string iso, DateTime fallbackUtc)
        {
            if (!string.IsNullOrEmpty(iso) &&
                DateTime.TryParse(iso, CultureInfo.InvariantCulture,
                    DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out var parsed))
            {
                return DateTime.SpecifyKind(parsed, DateTimeKind.Utc);
            }
            return fallbackUtc;
        }

        static string GuessMime(string ext)
        {
            switch ((ext ?? string.Empty).ToLowerInvariant())
            {
                case ".jpg":
                case ".jpeg": return "image/jpeg";
                case ".png": return "image/png";
                case ".heic": return "image/heic";
                case ".heif": return "image/heif";
                case ".webp": return "image/webp";
                default: return "application/octet-stream";
            }
        }
    }

    /// <summary>
    /// The device photo gallery, over <see cref="GalleryPicker"/> (yasirkula's
    /// NativeGallery on device, a file dialog in the Editor).
    ///
    /// <para>The picker reports a user cancel and an OS permission denial
    /// identically — both arrive as a null path — so both map to
    /// <see cref="PhotoPickOutcome.Cancelled"/>. That is the honest mapping: the
    /// app cannot tell them apart without a separate permission query, and
    /// showing "acesso negado" after a plain cancel would be a lie.</para>
    /// </summary>
    public sealed class GalleryPhotoPickerAdapter : IPhotoPicker
    {
        public void PickPhoto(Action<PhotoPickResult> onResult)
        {
            if (onResult == null) return;
            GalleryPicker.PickImage((path, error) =>
            {
                if (!string.IsNullOrEmpty(error))
                {
                    onResult(error == "cancelled"
                        ? PhotoPickResult.Cancelled()
                        : PhotoPickResult.Failed(error));
                    return;
                }

                long size = 0;
                try { size = new FileInfo(path).Length; }
                catch (Exception e)
                {
                    // Unknown size: 0 passes the limit check rather than blocking a
                    // pick over a stat failure. The backend still bounds the upload.
                    Debug.LogWarning($"[PhotoPicker] Could not stat {path}: {e.Message}");
                }
                onResult(PhotoPickResult.Picked(path, size));
            });
        }
    }

    /// <summary>
    /// The scene's <c>AnimalViewerRig</c> behind <see cref="ISpeciesModelViewer"/> —
    /// the Espécie screen's 3D turntable (Decision D1).
    ///
    /// <para><b>The framing logic is PORTED, not rewritten.</b>
    /// <see cref="MountModel"/>/<see cref="CenterAndFit"/> are
    /// <c>AnimalsScreenController.SpawnViewerInstance</c> /
    /// <c>CenterOnTurntable</c> / <c>FitCameraToBounds</c>, line for line: mount under
    /// the turntable, apply the AnimalDef's offset and scale, re-layer the whole
    /// hierarchy onto <c>AnimalViewer</c>, union every <c>Renderer.bounds</c> and
    /// translate so the VISIBLE body centres on the turntable (which is what hides
    /// each FBX's own pivot offset), then move the camera along its existing direction
    /// to <c>(maxDim/2)/tan(fov/2) × 1.15</c>. That is well-tuned code — it is what
    /// makes a 4 m hammerhead and a 2.5 m lemon shark frame the same — and
    /// <b>the prefab's rotation is deliberately NOT reset</b>, so the Y=180 dialled
    /// into the hammerhead prefab carries through here exactly as it does in AR.</para>
    ///
    /// <para><b>The one deliberate change from the legacy viewer is the zoom clamp.</b>
    /// <c>AnimalViewerInput</c> clamped to an absolute 0.5–10 m, which sits almost on
    /// top of the ~7.3 m the auto-fit picks for a 4 m animal — so the user's first
    /// pinch-out hit the stop. The clamp is relative to the fit distance instead, which
    /// is the only formulation that works across a catalog whose members differ 2× in
    /// length.</para>
    ///
    /// <para><b>Anti-aliasing: the render target stays single-sample.</b> URP resolves
    /// its own MSAA (from the URP asset, max 4 on Android) into the target, so a
    /// multisampled target is what produces "Attachment 0 was created with N samples
    /// but M samples were requested" every frame and an un-sampleable texture on most
    /// mobile GPUs — see CLAUDE.md, "Anti-aliasing in the viewer". The descriptor is
    /// copied from the authored asset (already 1) and <c>msaaSamples</c> is then forced
    /// to 1 anyway, so the invariant survives someone editing that asset.</para>
    /// </summary>
    public sealed class SpeciesModelViewerAdapter : ISpeciesModelViewer, IDisposable
    {
        const string RigName = "AnimalViewerRig";
        const string TurntableName = "Turntable";
        const string ViewerLayerName = "AnimalViewer";

        /// <summary>Breathing room around the fitted bounds — the legacy viewer's value.</summary>
        const float FitPadding = 1.15f;

        /// <summary>Zoom range as a multiple of the auto-fit distance — see the class remarks.</summary>
        const float MinZoomFactor = 0.35f;
        const float MaxZoomFactor = 2.5f;

        /// <summary>Fallback absolute clamp, used only before anything is fitted.</summary>
        const float FallbackMinDistance = 0.5f;
        const float FallbackMaxDistance = 12f;

        const float RotateDegreesPerPixel = 0.4f;
        const int MinTargetSide = 128;
        const int MaxTargetSide = 2048;

        readonly GameObject rig;
        readonly Camera camera;
        readonly Transform turntable;

        /// <summary>The RenderTexture asset serialized on the camera. Never rendered
        /// into — it is only the descriptor template and the thing to restore on the
        /// way out, so the scene is left as the builder made it.</summary>
        readonly RenderTexture authoredTarget;

        RenderTexture runtimeTarget;
        GameObject mounted;
        float fitDistance;

        /// <summary>Half the worst-case footprint the mounted body sweeps in the
        /// horizontal plane, and half its height. Kept so the camera can be re-fitted
        /// when the VIEWPORT changes shape without re-measuring the renderers — see
        /// <see cref="FitCamera"/>.</summary>
        float modelRadiusHorizontal;
        float modelRadiusVertical;

        bool disposed;

        public event Action TextureChanged;

        /// <summary>
        /// <paramref name="viewerRig"/> is the scene-root <c>AnimalViewerRig</c>, which
        /// is normally INACTIVE — hence <c>GetComponentInChildren(true)</c>. Null (no
        /// rig in this scene, or an editor context with no scene at all) leaves the
        /// adapter permanently unavailable, which the screen renders as "no 3D
        /// section".
        /// </summary>
        public SpeciesModelViewerAdapter(GameObject viewerRig)
        {
            rig = viewerRig;
            if (rig == null) return;

            camera = rig.GetComponentInChildren<Camera>(true);
            turntable = FindDescendant(rig.transform, TurntableName);
            if (camera != null) authoredTarget = camera.targetTexture;

            if (camera == null || turntable == null)
            {
                Debug.LogWarning(
                    $"[SpeciesModelViewer] {RigName} is missing its " +
                    (camera == null ? "ViewerCamera" : TurntableName) +
                    " — the 3D section will be hidden. Re-run Tools > Mergulho Virtual > Create Animal Viewer Rig.");
            }
        }

        public bool IsAvailable => rig != null && camera != null && turntable != null;

        public Texture Texture => runtimeTarget;

        public bool Show(string speciesKey)
        {
            if (!IsAvailable || string.IsNullOrEmpty(speciesKey)) return false;

            var animal = Resources.Load<AnimalDef>("Animals/" + speciesKey);
            if (animal == null || animal.prefab == null)
            {
                // Not an error to surface: a missing prefab slot is the documented
                // fallout of replacing a species' FBX, and the screen's answer is to
                // drop the section.
                Debug.LogWarning($"[SpeciesModelViewer] No 3D model for \"{speciesKey}\" — its AnimalDef prefab slot is empty or the asset is missing.");
                return false;
            }

            rig.SetActive(true);
            MountModel(animal);
            return true;
        }

        public void Hide()
        {
            DestroyMounted();
            ReleaseRuntimeTarget();
            if (rig != null && rig.activeSelf) rig.SetActive(false);
        }

        public void SetViewportSize(int widthPx, int heightPx)
        {
            if (!IsAvailable) return;
            int w = Mathf.Clamp(widthPx, MinTargetSide, MaxTargetSide);
            int h = Mathf.Clamp(heightPx, MinTargetSide, MaxTargetSide);
            if (runtimeTarget != null && runtimeTarget.width == w && runtimeTarget.height == h) return;

            var next = CreateTarget(w, h);
            if (next == null) return;

            camera.targetTexture = next;
            var previous = runtimeTarget;
            runtimeTarget = next;
            DestroyTarget(previous);

            // The framing is a function of the target's ASPECT, and the first target
            // arrives after the model is mounted (the screen pushes the viewport size
            // once it has a resolved layout). Without this the animal would be framed
            // against whatever shape the authored RenderTexture happens to be. Re-fit
            // only ever happens on a real size change — SetViewportSize returns early
            // otherwise — so it cannot walk over a zoom the user is in the middle of.
            if (mounted != null) FitCamera();

            TextureChanged?.Invoke();
        }

        public void Rotate(float pixelsX)
        {
            if (!IsAvailable || Mathf.Approximately(pixelsX, 0f)) return;
            // Negated so the model follows the finger: dragging right spins the near
            // side right. Same sign convention as the uGUI viewer.
            turntable.Rotate(0f, -pixelsX * RotateDegreesPerPixel, 0f, Space.World);
        }

        public void Zoom(float metres)
        {
            if (!IsAvailable || Mathf.Approximately(metres, 0f)) return;

            Vector3 toCamera = camera.transform.position - turntable.position;
            float current = toCamera.magnitude;
            if (current < 0.0001f) return;

            float min = fitDistance > 0f ? fitDistance * MinZoomFactor : FallbackMinDistance;
            float max = fitDistance > 0f ? fitDistance * MaxZoomFactor : FallbackMaxDistance;
            float next = Mathf.Clamp(current + metres, min, max);

            camera.transform.position = turntable.position + toCamera.normalized * next;
            camera.transform.LookAt(turntable.position);
        }

        public void Dispose()
        {
            if (disposed) return;
            disposed = true;
            Hide();
            if (camera != null) camera.targetTexture = authoredTarget;
        }

        // ---- Mounting + framing (ported from AnimalsScreenController) ---------

        void MountModel(AnimalDef animal)
        {
            DestroyMounted();

            mounted = UnityEngine.Object.Instantiate(animal.prefab, turntable);
            // Position and scale are overwritten; ROTATION is deliberately left as the
            // prefab authored it — see the class remarks.
            mounted.transform.localPosition = animal.viewerOffset;
            mounted.transform.localScale = animal.viewerScale;

            int layer = LayerMask.NameToLayer(ViewerLayerName);
            if (layer >= 0) SetLayerRecursively(mounted, layer);
            else Debug.LogWarning($"[SpeciesModelViewer] Layer '{ViewerLayerName}' not found — add it under Project Settings > Tags and Layers.");

            CenterAndFit(mounted);
        }

        /// <summary>
        /// Unions every <c>Renderer.bounds</c> and translates the instance so the
        /// VISIBLE body sits on the turntable, then fits the camera to it. Centring on
        /// the rendered bounds rather than the transform is what hides each FBX's own
        /// pivot offset — and it is also what makes the user's drag orbit the animal
        /// instead of some point inside its tail.
        ///
        /// <para>Caveat carried over with the code: a
        /// <c>SkinnedMeshRenderer</c>'s bounds are the BIND POSE AABB (Unity computes
        /// them at import while <c>updateWhenOffscreen</c> is false), so a wide tail
        /// sweep can shift the centroid a couple of centimetres between animation
        /// frames. Invisible in practice; if it ever visibly jitters on entry, that
        /// flag on the species' renderer is the fix.</para>
        /// </summary>
        void CenterAndFit(GameObject instance)
        {
            var renderers = instance.GetComponentsInChildren<Renderer>();
            if (renderers.Length == 0) return;

            Bounds bounds = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; i++) bounds.Encapsulate(renderers[i].bounds);

            instance.transform.position += turntable.position - bounds.center;

            Vector3 size = bounds.size;
            if (Mathf.Max(size.x, size.y, size.z) <= 0f) return;

            // Horizontal radius is the circle the XZ footprint sweeps, not size.x:
            // the turntable rotates about Y and the user will spin it, so the fit has
            // to hold in every orientation or the nose clips mid-drag.
            modelRadiusHorizontal = 0.5f * Mathf.Sqrt(size.x * size.x + size.z * size.z);
            modelRadiusVertical = 0.5f * size.y;

            FitCamera();
        }

        /// <summary>
        /// Puts the camera at the distance where the mounted body just fits, on
        /// whichever axis actually binds.
        ///
        /// <para><b>The bug this replaces.</b> The port from the uGUI viewer fitted
        /// the animal's LONGEST dimension against <see cref="Camera.fieldOfView"/>,
        /// which is the VERTICAL field — the short axis of a 358x260 viewport. A 4 m
        /// shark lying horizontally therefore landed at the distance where its length
        /// filled the HEIGHT, covering about 63% of the width and 22% of the height:
        /// roughly a seventh of the box, with the rest empty, and no amount of
        /// viewport height would have fixed it because the mismatch is structural.
        /// Fitting both axes and taking the larger distance frames it at ~84% of the
        /// width instead; the remaining margin is a long thin animal in a 1.38:1 box,
        /// which is geometry, not a bug.</para>
        ///
        /// <para><see cref="FitPadding"/> keeps its role unchanged — breathing room
        /// applied once, to whichever requirement won.</para>
        /// </summary>
        void FitCamera()
        {
            if (!IsAvailable) return;
            if (modelRadiusHorizontal <= 0f && modelRadiusVertical <= 0f) return;

            float tanVertical = Mathf.Tan(camera.fieldOfView * 0.5f * Mathf.Deg2Rad);
            if (tanVertical <= 0.0001f) return;
            float tanHorizontal = tanVertical * TargetAspect();
            if (tanHorizontal <= 0.0001f) return;

            float distance = Mathf.Max(
                modelRadiusVertical / tanVertical,
                modelRadiusHorizontal / tanHorizontal) * FitPadding;
            if (distance <= 0f) return;

            fitDistance = distance;

            Vector3 toCamera = camera.transform.position - turntable.position;
            if (toCamera.sqrMagnitude < 0.0001f) toCamera = -turntable.forward;
            camera.transform.position = turntable.position + toCamera.normalized * fitDistance;
            camera.transform.LookAt(turntable.position);
        }

        /// <summary>
        /// Width ÷ height of what the camera is actually rendering into. Read off the
        /// runtime target rather than <see cref="Camera.aspect"/> so it is right even
        /// on the frame the target is swapped, and falls back to the camera's own
        /// value (then 1) before the first viewport size arrives.
        /// </summary>
        float TargetAspect()
        {
            if (runtimeTarget != null && runtimeTarget.height > 0)
                return (float)runtimeTarget.width / runtimeTarget.height;

            float aspect = camera.aspect;
            return !float.IsNaN(aspect) && aspect > 0.01f ? aspect : 1f;
        }

        void DestroyMounted()
        {
            if (mounted == null) return;
            UnityEngine.Object.Destroy(mounted);
            mounted = null;
            fitDistance = 0f;
            modelRadiusHorizontal = 0f;
            modelRadiusVertical = 0f;
        }

        // ---- Render target ---------------------------------------------------

        RenderTexture CreateTarget(int width, int height)
        {
            RenderTextureDescriptor descriptor;
            if (authoredTarget != null)
            {
                descriptor = authoredTarget.descriptor;
            }
            else
            {
                descriptor = new RenderTextureDescriptor(width, height, RenderTextureFormat.Default, 24);
                descriptor.sRGB = true;
            }
            descriptor.width = width;
            descriptor.height = height;
            // Non-negotiable — see the class remarks on anti-aliasing.
            descriptor.msaaSamples = 1;
            descriptor.bindMS = false;

            var target = new RenderTexture(descriptor) { name = "SpeciesModelViewer (runtime)" };
            if (authoredTarget != null)
            {
                target.filterMode = authoredTarget.filterMode;
                target.wrapMode = authoredTarget.wrapMode;
            }
            if (!target.Create())
            {
                Debug.LogWarning($"[SpeciesModelViewer] Could not create a {width}x{height} render target.");
                UnityEngine.Object.Destroy(target);
                return null;
            }
            return target;
        }

        void ReleaseRuntimeTarget()
        {
            if (runtimeTarget == null) return;
            if (camera != null && camera.targetTexture == runtimeTarget) camera.targetTexture = authoredTarget;
            var previous = runtimeTarget;
            runtimeTarget = null;
            DestroyTarget(previous);
            TextureChanged?.Invoke();
        }

        static void DestroyTarget(RenderTexture target)
        {
            if (target == null) return;
            target.Release();
            UnityEngine.Object.Destroy(target);
        }

        // ---- Scene helpers ---------------------------------------------------

        static Transform FindDescendant(Transform root, string name)
        {
            if (root.name == name) return root;
            for (int i = 0; i < root.childCount; i++)
            {
                var found = FindDescendant(root.GetChild(i), name);
                if (found != null) return found;
            }
            return null;
        }

        static void SetLayerRecursively(GameObject go, int layer)
        {
            go.layer = layer;
            foreach (Transform child in go.transform) SetLayerRecursively(child.gameObject, layer);
        }
    }

    /// <summary>
    /// One <c>VideoPlayer</c> behind <see cref="IVideoPlayback"/> — the Espécie
    /// screen's inline educational clips.
    ///
    /// <para><b>APIOnly render mode, no RenderTexture asset</b>, which is how the uGUI
    /// <c>VideoPlayerController</c> does it too: the decoder hands back a texture of
    /// the clip's own dimensions on <c>prepareCompleted</c>, so a vertical "reel" and
    /// a landscape clip both arrive correctly shaped and the screen letterboxes with
    /// <c>ScaleToFit</c>. Audio is <c>Direct</c>, so no AudioSource is needed.</para>
    ///
    /// <para><b>Nothing streams until the user taps.</b> <c>playOnAwake</c> is off and
    /// <c>Prepare()</c> is only called from <see cref="Play"/>, so a species page with
    /// two clips on it costs no bandwidth until somebody asks for one. A finished clip
    /// releases everything and returns the card to its poster
    /// (<see cref="VideoPlaybackState.Idle"/>) rather than sitting on a frozen last
    /// frame.</para>
    ///
    /// <para><b>Failures are logged here and summarised there.</b> Unity's messages are
    /// technical English, so the raw reason goes to the log (where logcat can see it)
    /// and the screen shows one fixed pt-BR line. On a <b>Linux editor every clip
    /// fails</b> — Unity's Linux VideoPlayer cannot decode H.264 and these are H.264 —
    /// so this path is only verifiable on an Android build, exactly like the Animais
    /// cards and the Instagram widget before it.</para>
    /// </summary>
    public sealed class VideoPlaybackAdapter : IVideoPlayback, IDisposable
    {
        readonly GameObject host;
        readonly UnityEngine.Video.VideoPlayer player;
        bool disposed;

        public event Action Changed;

        /// <summary>
        /// <paramref name="parent"/> is normally the AppUI GameObject, so the player
        /// lives and dies with the shell instead of leaking a scene root.
        /// </summary>
        public VideoPlaybackAdapter(Transform parent)
        {
            host = new GameObject("UiVideoPlayback");
            if (parent != null) host.transform.SetParent(parent, false);

            player = host.AddComponent<UnityEngine.Video.VideoPlayer>();
            player.source = UnityEngine.Video.VideoSource.Url;
            player.renderMode = UnityEngine.Video.VideoRenderMode.APIOnly;
            player.audioOutputMode = UnityEngine.Video.VideoAudioOutputMode.Direct;
            player.playOnAwake = false;
            player.isLooping = false;
            player.skipOnDrop = true;

            player.prepareCompleted += OnPrepared;
            player.errorReceived += OnError;
            player.loopPointReached += OnReachedEnd;
        }

        public bool IsAvailable => player != null;

        public string Url { get; private set; }

        public VideoPlaybackState State { get; private set; } = VideoPlaybackState.Idle;

        /// <summary>
        /// Null until prepared and again after <see cref="Stop"/>. Gated on
        /// <c>isPrepared</c> rather than on the state, because that is the flag the
        /// decoder itself sets.
        /// </summary>
        public Texture Texture => player != null && player.isPrepared ? player.texture : null;

        public double PositionSeconds => player != null && player.isPrepared ? player.time : 0d;

        public double DurationSeconds => player != null && player.isPrepared ? player.length : 0d;

        public void Play(string url)
        {
            if (player == null || string.IsNullOrWhiteSpace(url)) return;

            // Resume in place: the same clip, already buffered and paused.
            if (url == Url && State == VideoPlaybackState.Paused && player.isPrepared)
            {
                player.Play();
                Set(VideoPlaybackState.Playing);
                return;
            }

            // Anything else — a different clip, or a retry after a failure — starts
            // over. Stopping first is what releases the previous stream.
            player.Stop();
            Url = url;
            player.url = url;
            Set(VideoPlaybackState.Loading);
            player.Prepare();
        }

        public void Pause()
        {
            if (player == null || State != VideoPlaybackState.Playing) return;
            player.Pause();
            Set(VideoPlaybackState.Paused);
        }

        public void Stop()
        {
            if (player == null) return;
            bool wasBound = State != VideoPlaybackState.Idle || Url != null;
            player.Stop();
            Url = null;
            State = VideoPlaybackState.Idle;
            if (wasBound) Changed?.Invoke();
        }

        public void Seek(double seconds)
        {
            if (player == null || !player.isPrepared) return;
            double length = player.length;
            if (!(length > 0d)) return;
            player.time = Math.Max(0d, Math.Min(seconds, length));
            Changed?.Invoke();
        }

        public void Dispose()
        {
            if (disposed) return;
            disposed = true;
            if (player != null)
            {
                player.prepareCompleted -= OnPrepared;
                player.errorReceived -= OnError;
                player.loopPointReached -= OnReachedEnd;
                player.Stop();
            }
            if (host != null) UnityEngine.Object.Destroy(host);
        }

        void OnPrepared(UnityEngine.Video.VideoPlayer source)
        {
            // A stale callback from a stream the screen has already left behind.
            if (State != VideoPlaybackState.Loading) return;
            source.Play();
            Set(VideoPlaybackState.Playing);
        }

        void OnError(UnityEngine.Video.VideoPlayer source, string message)
        {
            Debug.LogWarning($"[VideoPlayback] {Url}: {message}");
            Set(VideoPlaybackState.Failed);
        }

        /// <summary>
        /// The clip ended. Releasing everything (rather than holding the last frame)
        /// returns the card to its poster with "Assistir" on it, which is what a
        /// viewer expects after a clip finishes, and it stops holding an open stream.
        /// </summary>
        void OnReachedEnd(UnityEngine.Video.VideoPlayer source) => Stop();

        void Set(VideoPlaybackState next)
        {
            State = next;
            Changed?.Invoke();
        }
    }
}
